package Frames;

import controles.ControlPlan;
import entidades.Plan;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author gabri
 */
public class FrmDuracionMesociclos extends javax.swing.JFrame {

    private Date inicio, fin;
    private int semanasEntreFechas;
    private Plan plan;

    ControlPlan controlPlan = new ControlPlan();

    /**
     * Creates new form FrmDuracionMesociclos
     */
    public FrmDuracionMesociclos() {
        initComponents();
    }

    public FrmDuracionMesociclos(Plan plan) {
        initComponents();
        this.plan = plan;
    }

    public void recopilarInfo() {
        if (!controlPlan.fechaVacia(jDateChooser1.getDate(), dateChooserFinPlan.getDate())) {
            inicio = new Date(jDateChooser1.getDate().getTime());
            fin = new Date(dateChooserFinPlan.getDate().getTime());

            Date fechaActualDate = new Date(2023 - 1900, 11, 7);

            // Convert java.sql.Date to LocalDate
            LocalDate inicioLocalDate = inicio.toLocalDate();

            // Convert java.sql.Date to LocalDate
            LocalDate finLocalDate = fin.toLocalDate();

            LocalDate actualLocalDate = fechaActualDate.toLocalDate();

            semanasEntreFechas = (int) ChronoUnit.WEEKS.between(inicioLocalDate, finLocalDate);

            txtSemanas.setText(String.valueOf(semanasEntreFechas));

            if (actualLocalDate.isAfter(inicioLocalDate) || actualLocalDate.isAfter(finLocalDate)) {
                JOptionPane.showMessageDialog(this, "La fecha fin e inicio no pueden estar antes de " + actualLocalDate + ".", "Erorr", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (finLocalDate.isBefore(inicioLocalDate) || (finLocalDate.isEqual(inicioLocalDate))) {
                // Manejar el caso en el que la fecha de fin es anterior a la fecha de inicio
                JOptionPane.showMessageDialog(this, "La fecha de fin debe ser posterior a la fecha de inicio.", "Error", JOptionPane.ERROR_MESSAGE);
                return; // No continuar con el proceso
            }

            if (inicioLocalDate.isBefore(actualLocalDate) || (finLocalDate.isBefore(actualLocalDate))) {
                // Manejar el caso en el que la fecha de fin es anterior a la fecha de inicio
                JOptionPane.showMessageDialog(this, "La fecha de fin e inicio debe ser posterior a la fecha actual.", "Error", JOptionPane.ERROR_MESSAGE);
                return; // No continuar con el proceso
            }
            //Validación faltante
            if (inicioLocalDate.equals(finLocalDate)) {
                JOptionPane.showMessageDialog(this, "La fecha fin e inicio deben ser distintas una de otra.", "Erorr", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (semanasEntreFechas < 15) {
                JOptionPane.showMessageDialog(this, "No hay semanas suficientes. Debe ser mayor a 15. Actualmente: " + semanasEntreFechas, "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int confirmar = JOptionPane.showConfirmDialog(null, "Total de semanas: " + semanasEntreFechas, "Total de semanas", JOptionPane.YES_NO_OPTION);
            if (confirmar == JOptionPane.YES_OPTION) {
                plan.setInicio(inicio);
                plan.setFin(fin);

                System.out.println(plan.getFin());
                controlPlan.agregarPlan(plan);
                this.dispose();
                FrmSemEtapas fE = new FrmSemEtapas(inicio, fin, semanasEntreFechas);
                fE.setVisible(true);
            } else {
            }
//           

        } else {
            JOptionPane.showMessageDialog(this, "Hay campos vacíos", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoTitulo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        dateChooserFinPlan = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtSemanas = new javax.swing.JTextField();
        btnContinuar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FondoTitulo.setEditable(false);
        FondoTitulo.setBackground(new java.awt.Color(156, 164, 175));
        FondoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FondoTituloActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(56, 133, 185));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Total de semanas:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(180, 180, 150, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Inicio del plan");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(70, 40, 150, 30);
        jPanel2.add(jDateChooser1);
        jDateChooser1.setBounds(50, 70, 180, 30);
        jPanel2.add(dateChooserFinPlan);
        dateChooserFinPlan.setBounds(440, 70, 200, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Fin del plan");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(490, 40, 150, 30);

        txtSemanas.setEditable(false);
        txtSemanas.setText("0");
        jPanel2.add(txtSemanas);
        txtSemanas.setBounds(340, 190, 71, 22);

        btnContinuar.setBackground(new java.awt.Color(56, 133, 185));
        btnContinuar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContinuar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(56, 133, 185));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoTitulo)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(FondoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FondoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FondoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FondoTituloActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        FrmMesociclo frmC = new FrmMesociclo();
        frmC.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        this.recopilarInfo();

    }//GEN-LAST:event_btnContinuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FondoTitulo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnContinuar;
    private com.toedter.calendar.JDateChooser dateChooserFinPlan;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtSemanas;
    // End of variables declaration//GEN-END:variables
}
