package Frames;

import controles.ControlMedio;
import entidades.Medio;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;

/**
 *
 * @author Alexandra c:
 */
public class FrmElecMedios extends javax.swing.JFrame {

    List<String> listaJCB = new ArrayList<>();
    List<Medio> listaMedios = new ArrayList<>();
    ControlMedio controlMedio = new ControlMedio();
    int eG = 0, eE = 0, eC = 0;

    /**
     * Creates new form FrmElecMedios
     */
    public FrmElecMedios() {
        initComponents();
    }
    
    public FrmElecMedios(int eG, int eE, int eC) {
        initComponents();
        this.eG = eG;
        this.eE = eE;
        this.eC = eC;
        jPanel2.setLayout(new GridLayout(0, 1)); 
        listaMedios = controlMedio.consultarRamas();

        for (Medio elemento : listaMedios) {
            JCheckBox checkBox = new JCheckBox(elemento.toString());
            jPanel2.add(checkBox); // Agrega el checkbox al panel
        }
    }

    public FrmElecMedios(String[] arreglo) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FondoTitulo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblApartado = new javax.swing.JLabel();
        Flexibilidad = new javax.swing.JCheckBox();
        RAG = new javax.swing.JCheckBox();
        RAE = new javax.swing.JCheckBox();
        ResVelGen = new javax.swing.JCheckBox();
        ResVelEsp = new javax.swing.JCheckBox();
        FuerzaGen = new javax.swing.JCheckBox();
        CoordinacionTecnica = new javax.swing.JCheckBox();
        VelGeneral = new javax.swing.JCheckBox();
        VelEspecial = new javax.swing.JCheckBox();
        FuerzaEsp = new javax.swing.JCheckBox();
        btnCancelar = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        lblCriterioBusqueda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Medios a practicar");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        FondoTitulo.setEditable(false);
        FondoTitulo.setBackground(new java.awt.Color(156, 164, 175));
        FondoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FondoTituloActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(56, 133, 185));
        jPanel2.setLayout(null);

        lblApartado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblApartado.setText("Medios Físicos a practicar");
        jPanel2.add(lblApartado);
        lblApartado.setBounds(350, 20, 310, 30);

        Flexibilidad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Flexibilidad.setText("FLEXIBILIDAD (MIN)");
        jPanel2.add(Flexibilidad);
        Flexibilidad.setBounds(660, 220, 230, 20);

        RAG.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RAG.setText("RAG (KM)");
        jPanel2.add(RAG);
        RAG.setBounds(70, 90, 170, 20);

        RAE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RAE.setText("RAE (MIN)");
        jPanel2.add(RAE);
        RAE.setBounds(70, 150, 170, 20);

        ResVelGen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ResVelGen.setText("RES. VEL. GEN(MTROS)");
        jPanel2.add(ResVelGen);
        ResVelGen.setBounds(360, 90, 240, 20);

        ResVelEsp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ResVelEsp.setText("RES. VEL. ESP(MIN)");
        jPanel2.add(ResVelEsp);
        ResVelEsp.setBounds(360, 150, 210, 20);

        FuerzaGen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FuerzaGen.setText("FUERZA GEN(REP)");
        jPanel2.add(FuerzaGen);
        FuerzaGen.setBounds(360, 210, 230, 20);

        CoordinacionTecnica.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CoordinacionTecnica.setText("COORDINACIÓN TÉCNICA (REP)");
        jPanel2.add(CoordinacionTecnica);
        CoordinacionTecnica.setBounds(660, 150, 320, 20);

        VelGeneral.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        VelGeneral.setText("VEL. GENERAL (Mtros)");
        jPanel2.add(VelGeneral);
        VelGeneral.setBounds(70, 210, 230, 20);

        VelEspecial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        VelEspecial.setText("VEL. ESPECIAL (SEG)");
        jPanel2.add(VelEspecial);
        VelEspecial.setBounds(70, 270, 220, 20);

        FuerzaEsp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FuerzaEsp.setText("FUERZA ESP(REP)");
        jPanel2.add(FuerzaEsp);
        FuerzaEsp.setBounds(360, 270, 200, 20);

        btnCancelar.setBackground(new java.awt.Color(56, 133, 185));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnContinuar.setBackground(new java.awt.Color(56, 133, 185));
        btnContinuar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContinuar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        lblCriterioBusqueda.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCriterioBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        lblCriterioBusqueda.setText("Criterios de Búsqueda");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(lblCriterioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161)
                        .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(FondoTitulo)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 984, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(FondoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCriterioBusqueda)
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FondoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FondoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FondoTituloActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed

        revisarCheckedBox();
        FrmCalculadora calculadora = new FrmCalculadora(listaJCB, eG, eE, eC);
        this.dispose();
        calculadora.setVisible(true);
    }//GEN-LAST:event_btnContinuarActionPerformed

    public void revisarCheckedBox() {
        listaJCB = new ArrayList<>();
        if (RAG.isSelected()) {
            String rag = RAG.getText();
            listaJCB.add(rag);
        }
        if (RAE.isSelected()) {
            String rae = RAE.getText();
            listaJCB.add(rae);
        }
        if (VelGeneral.isSelected()) {
            String velGeneral = VelGeneral.getText();
            listaJCB.add(velGeneral);
        }
        if (VelEspecial.isSelected()) {
            String velEspecial = VelEspecial.getText();
            listaJCB.add(velEspecial);
        }
        if (ResVelGen.isSelected()) {
            String resVelGen = ResVelGen.getText();
            listaJCB.add(resVelGen);
        }
        if (ResVelEsp.isSelected()) {
            String relVelEsp = ResVelEsp.getText();
            listaJCB.add(relVelEsp);
        }
        if (FuerzaGen.isSelected()) {
            String fuerzaGen = FuerzaGen.getText();
            listaJCB.add(fuerzaGen);
        }
        if (FuerzaEsp.isSelected()) {
            String fuerzaEsp = FuerzaEsp.getText();
            listaJCB.add(fuerzaEsp);
        }
        if (CoordinacionTecnica.isSelected()) {
            String coordTec = CoordinacionTecnica.getText();
            listaJCB.add(coordTec);
        }
        if (Flexibilidad.isSelected()) {
            String Flex = Flexibilidad.getText();
            listaJCB.add(Flex);
        }
        for (String string : listaJCB) {
            System.out.println(string);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CoordinacionTecnica;
    private javax.swing.JCheckBox Flexibilidad;
    private javax.swing.JTextField FondoTitulo;
    private javax.swing.JCheckBox FuerzaEsp;
    private javax.swing.JCheckBox FuerzaGen;
    private javax.swing.JCheckBox RAE;
    private javax.swing.JCheckBox RAG;
    private javax.swing.JCheckBox ResVelEsp;
    private javax.swing.JCheckBox ResVelGen;
    private javax.swing.JCheckBox VelEspecial;
    private javax.swing.JCheckBox VelGeneral;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblApartado;
    private javax.swing.JLabel lblCriterioBusqueda;
    // End of variables declaration//GEN-END:variables
}
