package Frames;

import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        menu3 = new javax.swing.JMenuBar();
        menuInicio3 = new javax.swing.JMenu();
        menuInicioSalirAplicacion3 = new javax.swing.JMenuItem();
        menuVentas = new javax.swing.JMenu();
        menuVentasVenta = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        menuConsultasVentas = new javax.swing.JMenuItem();
        menuConsultasProductos = new javax.swing.JMenuItem();
        menuConsultasProveedores = new javax.swing.JMenuItem();
        menuConsultasCategorias = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        menuPrincipal = new javax.swing.JMenuBar();
        menuInicio4 = new javax.swing.JMenu();
        menuInicioSalirAplicacion4 = new javax.swing.JMenuItem();
        menuVentas1 = new javax.swing.JMenu();
        menuVentasVenta1 = new javax.swing.JMenuItem();
        menuConsultas1 = new javax.swing.JMenu();
        menuConsultasVentas1 = new javax.swing.JMenuItem();
        menuConsultasProductos1 = new javax.swing.JMenuItem();
        menuConsultasProveedores1 = new javax.swing.JMenuItem();
        menuConsultasCategorias1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setTitle("Menu Principal");
        jFrame1.setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(163, 148, 132));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        jPanel1.setLayout(null);

        menu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        menuInicio3.setText("Inicio");

        menuInicioSalirAplicacion3.setText("Salir de la aplicación");
        menuInicioSalirAplicacion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInicioSalirAplicacion3ActionPerformed(evt);
            }
        });
        menuInicio3.add(menuInicioSalirAplicacion3);

        menu3.add(menuInicio3);

        menuVentas.setText("Ventas");

        menuVentasVenta.setText("Venta");
        menuVentasVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVentasVentaActionPerformed(evt);
            }
        });
        menuVentas.add(menuVentasVenta);

        menu3.add(menuVentas);

        menuConsultas.setText("Administración");

        menuConsultasVentas.setText("Ventas");
        menuConsultasVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasVentasActionPerformed(evt);
            }
        });
        menuConsultas.add(menuConsultasVentas);

        menuConsultasProductos.setText("Productos");
        menuConsultasProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasProductosActionPerformed(evt);
            }
        });
        menuConsultas.add(menuConsultasProductos);

        menuConsultasProveedores.setText("Proveedores");
        menuConsultasProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasProveedoresActionPerformed(evt);
            }
        });
        menuConsultas.add(menuConsultasProveedores);

        menuConsultasCategorias.setText("Categorías");
        menuConsultasCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasCategoriasActionPerformed(evt);
            }
        });
        menuConsultas.add(menuConsultasCategorias);

        menu3.add(menuConsultas);

        jFrame1.setJMenuBar(menu3);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1320, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(163, 148, 132));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        jPanel2.setLayout(null);

        menuPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        menuInicio4.setText("Inicio");

        menuInicioSalirAplicacion4.setText("Salir de la aplicación");
        menuInicioSalirAplicacion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInicioSalirAplicacion4ActionPerformed(evt);
            }
        });
        menuInicio4.add(menuInicioSalirAplicacion4);

        menuPrincipal.add(menuInicio4);

        menuVentas1.setText("Macros");

        menuVentasVenta1.setText("Venta");
        menuVentas1.add(menuVentasVenta1);

        menuPrincipal.add(menuVentas1);

        menuConsultas1.setText("Planes");

        menuConsultasVentas1.setText("Ventas");
        menuConsultasVentas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasVentas1ActionPerformed(evt);
            }
        });
        menuConsultas1.add(menuConsultasVentas1);

        menuConsultasProductos1.setText("Productos");
        menuConsultasProductos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasProductos1ActionPerformed(evt);
            }
        });
        menuConsultas1.add(menuConsultasProductos1);

        menuConsultasProveedores1.setText("Proveedores");
        menuConsultasProveedores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasProveedores1ActionPerformed(evt);
            }
        });
        menuConsultas1.add(menuConsultasProveedores1);

        menuConsultasCategorias1.setText("Categorías");
        menuConsultasCategorias1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultasCategorias1ActionPerformed(evt);
            }
        });
        menuConsultas1.add(menuConsultasCategorias1);

        menuPrincipal.add(menuConsultas1);

        jMenu1.setText("Calculadora Volumen");
        menuPrincipal.add(jMenu1);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuInicioSalirAplicacion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInicioSalirAplicacion3ActionPerformed
        int a = JOptionPane.YES_NO_OPTION;
        int resultado = JOptionPane.showConfirmDialog(this, "¿DESEA CERRAR LA APLICACIÓN?", "SALIR", a);
        if (resultado == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuInicioSalirAplicacion3ActionPerformed

    private void menuVentasVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVentasVentaActionPerformed
        FrmVentasAgregar frmVenta = new FrmVentasAgregar(usuarioLogueado);
        frmVenta.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                // Aquí es donde se ejecutará el código cuando se cierre el FrmVentasAgregar
                setVisible(true); // Hace visible el FrmPrincipal
            }
        });
        frmVenta.setVisible(true);
        setVisible(false); // Oculta el FrmPrincipal
    }//GEN-LAST:event_menuVentasVentaActionPerformed

    private void menuConsultasVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasVentasActionPerformed
        FrmVentasConsultar frmConsultarVentas = new FrmVentasConsultar(usuarioLogueado);
        frmConsultarVentas.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                // Aquí es donde se ejecutará el código cuando se cierre el FrmVentasConsultar
                setVisible(true); // Hace visible el FrmPrincipal
            }
        });
        frmConsultarVentas.setVisible(true);
        setVisible(false); // Oculta el FrmPrincipal
    }//GEN-LAST:event_menuConsultasVentasActionPerformed

    private void menuConsultasProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasProductosActionPerformed
        FrmProductos frmConsultarProductos = new FrmProductos();
        frmConsultarProductos.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                // Aquí es donde se ejecutará el código cuando se cierre el frmConsultarProductos
                setVisible(true); // Hace visible el FrmPrincipal
            }
        });
        frmConsultarProductos.setVisible(true);
        setVisible(false); // Oculta el FrmPrincipal

    }//GEN-LAST:event_menuConsultasProductosActionPerformed

    private void menuConsultasProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasProveedoresActionPerformed
        FrmProveedores consultarProveedores = new FrmProveedores();
        consultarProveedores.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                // Aquí es donde se ejecutará el código cuando se cierre el consultarProveedores
                setVisible(true); // Hace visible el FrmPrincipal
            }
        });
        consultarProveedores.setVisible(true);
        setVisible(false); // Oculta el FrmPrincipal
    }//GEN-LAST:event_menuConsultasProveedoresActionPerformed

    private void menuConsultasCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasCategoriasActionPerformed
        FrmCategorias consultarProveedores = new FrmCategorias();
        consultarProveedores.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                // Aquí es donde se ejecutará el código cuando se cierre el consultarProveedores
                setVisible(true); // Hace visible el FrmPrincipal
            }
        });
        consultarProveedores.setVisible(true);
        setVisible(false); // Oculta el FrmPrincipal
    }//GEN-LAST:event_menuConsultasCategoriasActionPerformed

    private void menuInicioSalirAplicacion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInicioSalirAplicacion4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuInicioSalirAplicacion4ActionPerformed

    private void menuConsultasVentas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasVentas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuConsultasVentas1ActionPerformed

    private void menuConsultasProductos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasProductos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuConsultasProductos1ActionPerformed

    private void menuConsultasProveedores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasProveedores1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuConsultasProveedores1ActionPerformed

    private void menuConsultasCategorias1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultasCategorias1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuConsultasCategorias1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuBar menu3;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuConsultas1;
    private javax.swing.JMenuItem menuConsultasCategorias;
    private javax.swing.JMenuItem menuConsultasCategorias1;
    private javax.swing.JMenuItem menuConsultasProductos;
    private javax.swing.JMenuItem menuConsultasProductos1;
    private javax.swing.JMenuItem menuConsultasProveedores;
    private javax.swing.JMenuItem menuConsultasProveedores1;
    private javax.swing.JMenuItem menuConsultasVentas;
    private javax.swing.JMenuItem menuConsultasVentas1;
    private javax.swing.JMenu menuInicio3;
    private javax.swing.JMenu menuInicio4;
    private javax.swing.JMenuItem menuInicioSalirAplicacion3;
    private javax.swing.JMenuItem menuInicioSalirAplicacion4;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu menuVentas;
    private javax.swing.JMenu menuVentas1;
    private javax.swing.JMenuItem menuVentasVenta;
    private javax.swing.JMenuItem menuVentasVenta1;
    // End of variables declaration//GEN-END:variables
}
